# .NET Runtime 이미지
# FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

# .NET SDK 이미지
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY . .
RUN dotnet restore REST_API.csproj
RUN dotnet build -c Release -o /app/build REST_API.csproj
RUN dotnet publish -c Release -o /app/publish REST_API.csproj

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
